name: Build LaTeX files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up TeX Live
      uses: actions/setup-latex@v1
      with:
        texlive-version: '2021'  # Puoi scegliere la versione di TeX Live che desideri

    - name: Find .tex files
      run: |
        files=$(find src -type f -name '*.tex') # Cerca file .tex nella cartella `src`
        if [ -z "$files" ]; then
          echo "No .tex files found. Exiting."
          exit 0
        fi
        echo "TEX_FILES=$(echo "$files" | sed 's/\n/ /g')" >> $GITHUB_ENV

    - name: Compile LaTeX files
      run: |
        for file in $TEX_FILES; do
          relative_path=${file#src/} # Rimuove il prefisso `src/`
          output_dir="PDF/$(dirname "$relative_path")" # Crea struttura cartelle
          mkdir -p "$output_dir"
          latexmk -pdf -output-directory="$output_dir" "$file"
          echo "Compiled $file to $output_dir"
        done

    - name: Upload PDF artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: PDF/
