name: LaTeX PDF Generator

on:
  push:
    paths:
      - '**/*.tex'  # Trigger su qualsiasi file .tex modificato
  workflow_dispatch:  # Trigger manuale

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Find all .tex files
      id: find-tex
      run: |
        files=$(find src -name '*.tex') # Cerca file .tex nella cartella `src`
        if [ -z "$files" ]; then
          echo "No .tex files found. Exiting."
          exit 0
        fi
        echo "TEX_FILES=$files" >> $GITHUB_ENV

    - name: Compile PDFs
      run: |
        for file in $TEX_FILES; do
          relative_path=${file#src/} # Rimuove il prefisso `src/`
          output_dir="PDF/$(dirname "$relative_path")" # Crea struttura cartelle
          mkdir -p "$output_dir"
          latexmk -pdf -output-directory="$output_dir" $file
          echo "Compiled $file to $output_dir"
        done
      env:
        TEX_FILES: ${{ env.TEX_FILES }}

    - name: Commit and push PDFs
      if: success()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add PDF/
        git commit -m "Add generated PDFs"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
