name: Convert LaTeX to PDF

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installa gli strumenti necessari
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full inkscape

      # Trova e converte i file SVG in PDF
      - name: Convert SVG to PDF
        run: |
          find ./src -name "*.svg" | while read svgfile; do
            pdf_file="${svgfile%.svg}.pdf"
            inkscape "$svgfile" --export-type=pdf --export-filename="$pdf_file"
          done

      # Compila i file LaTeX
      - name: Compile LaTeX files
        run: |
          mkdir -p PDF
          find ./src -name "*.tex" | while read texfile; do
            echo "Processing $texfile..."
            if grep -q "\\documentclass" "$texfile"; then
              pdflatex -interaction=nonstopmode -output-directory=PDF "$texfile" || echo "Error compiling $texfile"
            else
              echo "Skipping $texfile (missing \\documentclass)"
            fi
          done

      # Debug: Elenca i file generati
      - name: Debug PDF Directory
        run: |
          echo "Listing files in PDF directory:"
          ls -l PDF

      # Pulisci i file ausiliari
      - name: Clean up auxiliary files
        run: |
          find PDF -type f ! -name "*.pdf" -delete

      # Aggiungi i file PDF al commit
      - name: Commit compiled PDFs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add PDF/*.pdf
          git commit -m "Add compiled PDFs"
          git push
